[package]
edition = "2021"
name = "summa"
version = "0.5.5"
license-file = "LICENSE"
description = "Fast full-text search server"
homepage = "https://github.com/izihawa/summa"
repository = "https://github.com/izihawa/summa"
readme = "README.md"
keywords = ["async", "search", "server", "grpc"]

[[bin]]
name = "summa-server"
path = "src/bin/main.rs"
doc = false

[lib]
name = "summa"
path = "src/lib.rs"
doc = true

[badges]
maintenance = { status = "actively-developed" }

[build-dependencies]
tonic-build = { version = "0.7.2", default-features = false, features = ["prost", "transport"] }

[dev-dependencies]
tempdir = "0.3.7"

[dependencies]
async-broadcast = "0.4.0"
base64 = "0.13.0"
clap = { version = "3.1.18", features = ["cargo"] }
colored = "2.0.0"
config = "0.12.0"
crossbeam-channel = "0.5.4"
derive_builder = "0.11.1"
fasteval2 = { version = "2.0.2", features = ["unsafe-vars"] }
futures = "0.3.21"
futures-util = "0.3.21"
hyper = "0.14.17"
lazy_static = "1.4.0"
opentelemetry = "0.17.0"
opentelemetry-prometheus = "0.10.0"
parking_lot = { version = "0.12.0", features = ["send_guard"] }
path-absolutize = "3.0.13"
prometheus = "0.13.0"
prost = "0.10.3"
prost-types = "0.10.1"
rand = "0.8.5"
rdkafka = "0.28.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_derive = "1.0.136"
serde_json = "1.0.81"
serde_yaml = "0.8.23"
signal-hook = "0.3.13"
tantivy = { version = "0.18.0", features = ["brotli-compression"] }
tantivy-fst = "0.3.0"
textwrap = "0.15.0"
time = { version = "0.3.9", features = ["serde-well-known"] }
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full", "time"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
tonic = "0.7.2"
tonic-reflection = "0.4.0"
tower = "0.4.12"
tower-http = { version = "0.3.3", features = ["set-header", "trace"] }
tracing = "0.1.34"
tracing-appender = "0.2.2"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "json"] }
