[package]
name = "summa"
version = "0.1.0"
authors = ["Pasha Podolsky"]
license = "MIT"
categories = ["database-implementations", "data-structures"]
description = """Search engine server"""
documentation = "https://docs.rs/summa/"
homepage = "https://github.com/izihawa/summa"
repository = "https://github.com/izihawa/summa"
readme = "README.md"
keywords = ["search", "information", "retrieval"]
edition = "2018"

[dependencies]
actix-cors = "0.5.4"
actix-http = "2"
actix-rt = "1"
actix-service = "1"
actix-threadpool = "0.3"
actix-web = "3"
chrono = "0.4"
clap = "2"
colored = "2"
config = "0.11.0"
crossbeam = "0.8"
futures = "0.3"
libc = "0.2.79"
rand = "0.7"
regex = "1.4.2"
reopen = { version = "1", features = ["signals"] }
serde = "1"
serde_json = "1"
serde_qs = "0.7"
serde_yaml = "0.8"
signal-hook = "0.3.2"
slog = "2.5"
slog-async = "2.5"
slog-json = "2.3"
tantivy = { git = "https://github.com/izihawa/tantivy", branch = "master", features = ["brotli-compression"] }
textwrap = "0.12"
thiserror = "1"
tokio = { version = "0.2", features = ["full", "time"] }

[profile.release]
opt-level = 3
debug = false
debug-assertions = false

[profile.test]
debug-assertions = true
overflow-checks = true

[features]
build-binary = []
