[package]
edition = "2021"
name = "summa"
version = "0.4.0"
license-file = "LICENSE"
description = "Fast full-text search server"
homepage = "https://github.com/izihawa/summa"
repository = "https://github.com/izihawa/summa"
readme = "README.md"
keywords = ["async", "search", "server", "grpc"]

[[bin]]
name = "summa-server"
path = "src/bin/main.rs"
doc = false

[lib]
name = "summa"
path = "src/lib.rs"
doc = true

[badges]
maintenance = { status = "actively-developed" }

[build-dependencies]
tonic-build = { version = "0.6.2", default-features = false, features = ["prost", "transport"] }

[dependencies]
base64 = "0.13.0"
clap = { version = "3.1.6", features = ["cargo"] }
colored = "2.0.0"
config = "0.12.0"
crossbeam-channel = "0.5.4"
derive_builder = "0.11.1"
futures = "0.3.21"
futures-util = "0.3.21"
hyper = "0.14.17"
lazy_static = "1.4.0"
num_cpus = "1.13.1"
opentelemetry = "0.17.0"
opentelemetry-prometheus = "0.10.0"
parking_lot = { version = "0.12.0", features = ["send_guard"] }
path-absolutize = "3.0.13"
prometheus = "0.13.0"
prost = "0.9.0"
prost-types = "0.9.0"
rand = "0.8.5"
rdkafka = "0.28.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_derive = "1.0.136"
serde_json = "1.0.81"
serde_yaml = "0.8.23"
signal-hook = "0.3.13"
sqlite = "0.26.0"
tantivy = { version = "0.17.0", features = ["brotli-compression"], git = "https://github.com/izihawa/tantivy", branch = "main" }
tantivy-fst = "0.3.0"
textwrap = "0.15.0"
thiserror = "1.0.30"
tokio = { version = "1.17.0", features = ["full", "time"] }
tonic = "0.6.2"
tower = "0.4.12"
tower-http = { version = "0.2.5", features = ["set-header", "trace"] }
tracing = "0.1.32"
tracing-appender = "0.2.2"
tracing-futures = "0.2.5"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "json"] }
